; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = PoolMaster, SuperVisor

[common]
supervisor_firmware_version = '"1.4.1"'
poolmaster_firmware_version = '"4.7.1"'
nextion_firmware_version    = '"6.0.0"'

[env]
platform = espressif32@6.12.0 ; from https://github.com/platformio/platform-espressif32/releases
board = esp32doit-devkit-v1
framework = arduino
lib_compat_mode = strict
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
lib_ldf_mode = chain
debug_tool = esp-prog
debug_init_break = tbreak setup
upload_protocol = esptool
upload_port = COM4
board_build.partitions = min_spiffs.csv
extra_scripts = post:extra_script.py ; requires Python on VisualStudioCode or linux

[env:PoolMaster]
custom_version = ${common.poolmaster_firmware_version}
build_src_filter = +<./poolmaster>
build_flags =
	-D ESP32_DEVKITV1 
	-D CORE_DEBUG_LEVEL=0 
	-D FIRMW=${common.poolmaster_firmware_version} 
	-D TFT_FIRMW=${common.nextion_firmware_version}
	-D REVERSE_TANK_LEVEL ; use it only when Tank Level Sensor is inverted

lib_deps =
	ADS1115=https://lygte-info.dk/pic/Projects/ADS1115Library/ADS1115.zip
	Arduino_DebugUtils @ 1.4.0
	paulstoffregen/Time @ 1.6
	robtillaart/RunningMedian @ 0.3.9
	br3ttb/PID @ 1.2.1
	bblanchon/ArduinoJson @ 6.17.2
	milesburton/DallasTemperature @ 3.9.1
	marvinroger/AsyncMqttClient @ 0.9.0
;	mobizt/ESP Mail Client@^3.4.21
	rlogiacco/CircularBuffer@^1.4.0
	yiannisbourkelis/Uptime Library@^1.0.0
	https://github.com/adafruit/Adafruit_BME680
	https://github.com/adafruit/Adafruit_BMP280
	https://github.com/adafruit/Adafruit_SHT4x

[env:SuperVisor]
custom_version = ${common.supervisor_firmware_version}
build_src_filter = +<./supervisor>
build_flags =
	-D ESP32_DEVKITV1 
	-D SOC_I2C_SUPPORT_SLAVE=1 
	-D PMSV_VERSION=${common.supervisor_firmware_version}
	-D ELOG_SYSLOG_ENABLE=1
lib_deps =
	Time@^1.6.1
	elog 	; set a version once tested
	tzapu/WiFiManager@2.0.17
	ArduinoJson@7.4.2	; https://arduinojson.org/v7/revisions/
	yiannisbourkelis/Uptime Library@^1.0.0
	esp32async/AsyncTCP@3.4.4
	marvinroger/AsyncMqttClient@0.9.0
	esp32async/ESPAsyncWebServer@3.7.8
	https://github.com/adafruit/Adafruit-ST7735-Library
	https://github.com/adafruit/Adafruit-GFX-Library
